//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalTaskWcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebTracker
    {
        public long Id { get; set; }
        public string URLRequest { get; set; }
        public string SourceIp { get; set; }
        public Nullable<System.DateTime> TimeOfAction { get; set; }
    }
}
